name: Protective Parenting
favicon: null
layout_spectrum: 0.937788549810648
typography_spectrum: 0.23452739790081978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#444444'
    - '#8b8b8b'
    - '#acacac'
    - '#85cab7'
  brandStrength: 0.515292452648282
  lightness: 0.7307236578781158
  saturation: 0.8951724439393729
  rhythmicContrast: 0.15433228434994817
purpose: []
